# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
tags = Tag.create(
	[
		{ tag: "Components" },
		{ tag: "Cryosphere Science" },
		{ tag: "Culture" },
		{ tag: "Cyber security" },
		{ tag: "Data Management" },
		{ tag: "Debris" },
		{ tag: "Debris Detection" },
		{ tag: "Debris Mitigation" },
		{ tag: "Debris Removal" },
		{ tag: "Deep Space Communications" },
		{ tag: "Deep Space Navigation" },
		{ tag: "Deep Space Network" },
		{ tag: "Detectors and Instrument Systems" },
		{ tag: "Disaster management" },
		{ tag: "Distributed Systems" },
		{ tag: "DSN" },
		{ tag: "Dwarf planets" },
		{ tag: "Dynamics" },
		{ tag: "Earth Observation" },
		{ tag: "Earth Surface and Interior Science" },
		{ tag: "ECLSS" },
		{ tag: "Economics" },
		{ tag: "EDL" },
		{ tag: "Education" },
		{ tag: "Electric Propulsion" },
		{ tag: "Entry, decent, and landing" },
		{ tag: "Environmental Control" },
		{ tag: "Environmental Effects" },
		{ tag: "EVA" },
		{ tag: "Exoplanet Discovery and Science" },
		{ tag: "Experiments" },
		{ tag: "Exploration" },
		{ tag: "Extravehicular Activity" },
		{ tag: "Femtosats" },
		{ tag: "Fluid Dynamics" },
		{ tag: "Fluidic Systems" },
		{ tag: "GNC" },
		{ tag: "Government" },
		{ tag: "Government Spaceflight" },
		{ tag: "Gravity" },
		{ tag: "Guidance Navigation and Control" },
		{ tag: "Habitats" },
		{ tag: "Hall Thruster" },
		{ tag: "High Temperature Materials" },
		{ tag: "History" },
		{ tag: "Human Behavior" },
		{ tag: "Human Exploration" },
		{ tag: "Human Performance" },
		{ tag: "Human Spaceflight" },
		{ tag: "Hybrid propellant" },
		{ tag: "Hypersonic air-breathing" },
		{ tag: "Impacts" },
		{ tag: "In-Situ Planetary Exploration Systems" },
		{ tag: "In-Situ Resource Utilization" },
		{ tag: "Interplanetary" },
		{ tag: "Interstellar and Heliospheric Physics" },
		{ tag: "Interstellar missions" },
		{ tag: "Ion Propulsion" },
		{ tag: "ISRU" },
		{ tag: "ITAR" },
		{ tag: "Jupiter" },
		{ tag: "Kuiper Belt" },
		{ tag: "Large Aperture Systems" },
		{ tag: "Launch sites" },
		{ tag: "Launch vehicels" },
		{ tag: "Law" },
		{ tag: "Life Sciences" },
		{ tag: "Life Support" },
		{ tag: "Lifecycle Integrated Modeling and Simulation" },
		{ tag: "Liquid propellant" },
		{ tag: "Mars" },
		{ tag: "Materials" },
		{ tag: "Maternal Care" },
		{ tag: "Mechanical Systems" },
		{ tag: "Medical Care" },
		{ tag: "Mercury" },
		{ tag: "Microgravity" },
		{ tag: "Microsats" },
		{ tag: "Mission System Software" },
		{ tag: "Mobility & Robotics" },
		{ tag: "Modeling" },
		{ tag: "Moon" },
		{ tag: "Nanosats" },
		{ tag: "Nanotechnology" },
		{ tag: "Navigation" },
		{ tag: "Near Earth Objects" },
		{ tag: "NEOs" },
		{ tag: "Neptune" },
		{ tag: "NERVA" },
		{ tag: "Nuclear Power" },
		{ tag: "Nuclear Propulsion" },
		{ tag: "Ocean Science" },
		{ tag: "On-orbit servicing" },
		{ tag: "Oort Cloud" },
		{ tag: "Operations" },
		{ tag: "Optics" },
		{ tag: "Orbit Determination" },
		{ tag: "Orbit Propagation" },
		{ tag: "Origin of the Universe" },
		{ tag: "Outreach" },
		{ tag: "Physics" },
		{ tag: "Physiology" },
		{ tag: "Picosats" },
		{ tag: "Planetary Atmospheres" },
		{ tag: "Planetary Geology and Geophysics" },
		{ tag: "Plasma Thruster" },
		{ tag: "Pluto" },
		{ tag: "Policy" },
		{ tag: "Power" },
		{ tag: "Precision Formation Flying" },
		{ tag: "Propellant" },
		{ tag: "Propulsion" },
		{ tag: "Pyschology" },
		{ tag: "Pyschosociology" },
		{ tag: "Quality" },
		{ tag: "Radiation" },
		{ tag: "Radio Science" },
		{ tag: "Radioisotope Thermoelectric Generator" },
		{ tag: "Rapid Prototyping" },
		{ tag: "Regulations" },
		{ tag: "Risk Analysis" },
		{ tag: "Risk management" },
		{ tag: "Robotics" },
		{ tag: "RTG" },
		{ tag: "Safety" },
		{ tag: "Saturn" },
		{ tag: "SBSP" },
		{ tag: "SEP" },
		{ tag: "SETI" },
		{ tag: "Single-stage-to-orbit" },
		{ tag: "Small Satellites" },
		{ tag: "Smallsats" },
		{ tag: "Smart Materials" },
		{ tag: "Society" },
		{ tag: "Solar sails" },
		{ tag: "Solar System Ices and Icy Bodies" },
		{ tag: "Solar-Electric Propulsion" },
		{ tag: "Solid propellant" },
		{ tag: "Space elevators" },
		{ tag: "Space mineral resources" },
		{ tag: "Space-based Solar Power" },
		{ tag: "Spacecraft Protection" },
		{ tag: "Spectroscopy" },
		{ tag: "SSTO" },
		{ tag: "Structure of the Universe" },
		{ tag: "Structures" },
		{ tag: "Sun" },
		{ tag: "Survivable Systems for Extreme Environments" },
		{ tag: "Swarms" },
		{ tag: "Systems architectures" },
		{ tag: "Testing" },
		{ tag: "Tethers" },
		{ tag: "Thermal Systems" },
		{ tag: "Trajectory Optimization" },
		{ tag: "Transportation" },
		{ tag: "Uranus" },
		{ tag: "Validation" },
		{ tag: "Vehicles" },
		{ tag: "Venus" },
		{ tag: "Wireless Power Transmission" },
		{ tag: "Requirements"},
		{ tag: "Concepts"},
		{ tag: "ITAR"},
		{ tag: "Trade Studies"}
	])


#missions = Mission.create(
#	[
#		{"id":3,"name":"The Moon","description":"This envisioned \"moon village,\" a product of international collaboration between spacefaring nations, will be a base for science, business, mining and even tourism.","created_at":"2017-03-05T01:51:58.000Z","updated_at":"2017-04-04T01:16:20.000Z","cover_file_name":"moon.jpg","cover_content_type":"image/jpeg","cover_file_size":1115901,"cover_updated_at":"2017-03-24T00:42:02.000Z","objectives":"From the earliest astronomy to the space race, humankind has witnessed a constant evolution in the exploration and use of space. Now, with the International Space Station (ISS), an unparalleled level of cooperation has been achieved which has continued largely unaffected by any crises that may be occurring on Earth: many nations all pulling together, demonstrating day in, day out, just how important it is to invest in research and technology.\r\n\r\nThe paradigm shift that we see today in space activities is best encapsulated by the term ‘Space 4.0’, and the ‘Moon Village’ concept seeks to transform this paradigm shift into a set of concrete actions and create an environment where both international cooperation and the commercialisation of space can thrive.\r\n\r\nThe Moon Village concept was developed through a process of thorough analysis but it is vital to understand that what we are describing is neither a project nor a programme. By ‘Moon Village’ we do not mean a development planned around houses, some shops and a community centre. Rather, the term ‘village’ in this context refers this: a community created when groups join forces without first sorting out every detail, instead simply coming together with a view to sharing interests and capabilities.\r\n\r\nThe Moon Village is open to any and all interested parties and nations. There are no stipulations as to the form their participation might take: robotic and astronaut activities are equally sought after. You might see not only scientific and technological activities, but also activities based on exploiting resources or even tourism. It is precisely the open nature of the concept that would allow many nationalities to go to the Moon and take part while leaving behind them on Earth any differences of opinion.\r\n\r\nhttp://blogs.esa.int/janwoerner/2016/11/23/moon-village/","cover_dy":200},
#		{"id":4,"name":"Mars","description":"If we develop technological solutions that enable us to become a multi-planetary species and settle on Mars, we will then in parallel have breakthrough innovations for life and survivability on Earth.","created_at":"2017-03-08T18:15:20.000Z","updated_at":"2017-04-04T01:14:33.000Z","cover_file_name":"Mars_base_Illustration-n°5_by_Manchu.jpg","cover_content_type":"image/jpeg","cover_file_size":403133,"cover_updated_at":"2017-03-24T00:39:54.000Z","objectives":"Mars Direct is a sustained humans-to-Mars plan developed by Dr. Robert Zubrin that advocates a minimalist, live-off-the-land approach to exploring the planet Mars, allowing for maximum results with minimum investment.  Using existing launch technology and making use of the Martian atmosphere to generate rocket fuel, extracting water from the Martian soil and eventually using the abundant mineral resources of the Red Planet for construction purposes, the plan drastically lowers the amount of material which must be launched from Earth to Mars, thus sidestepping the primary stumbling block to space exploration and rapidly accelerating the timetable for human exploration of the solar system.\r\n\r\nThe general outline of Mars Direct is simple.  In the first year of implementation, an Earth Return Vehicle (ERV) is launched to Mars, arriving six months later.  Upon landing on the surface, a rover is deployed that contains the nuclear reactors necessary to generate rocket fuel for the return trip.  After 13 months, a fully-fueled ERV will be sitting on the surface of Mars.\r\n\r\nDuring the next launch window, 26 months after the ERV was launched, two more craft are sent up: a second ERV and a habitat module (hab), the astronauts’ ship.  This time the ERV is sent on a low-power trajectory, designed to arrive at Mars in eight months – so that it can land at the same site as the hab if the first ERV experiences any problems.  Assuming that the first ERV works as planned, the second ERV is landed at a different site, thus opening up another area of Mars for exploration by the next crew.\r\n\r\nAfter a year and a half on the Martian surface, the first crew returns to Earth, leaving behind the hab, the rovers associated with it and any ongoing experiments conducted there.  They land on Earth six months later to a hero’s welcome, with the next ERV/hab already on course for the Red Planet.  With two launches during each launch window – one ERV and one hab – more and more of Mars will be opened to human exploration.  Eventually multiple habs can be sent to the same site and linked together, allowing for the beginning of a permanent human settlement on the planet Mars.\r\n\r\nhttp://www.marssociety.org/home/about/mars-direct/","cover_dy":0},
#		{"id":5,"name":"Asteroids","description":"If we can mine asteroids we can vastly reduce costs of space travel.","created_at":"2017-03-08T18:15:46.000Z","updated_at":"2017-04-04T01:15:02.000Z","cover_file_name":"NASA-asteroid-capture.jpg","cover_content_type":"image/jpeg","cover_file_size":391657,"cover_updated_at":"2017-03-24T00:48:45.000Z","objectives":"Over the last hundred years, the human population has exploded from about 1.5 billion to more than seven billion, driving an ever-increasing demand for resources. To satisfy civilization's appetite, communities have expanded recycling efforts while mine operators must explore forbidding frontiers to seek out new deposits, opening mines miles underground or even at the bottom of the ocean.\r\n\r\nAsteroids could one day be a vast new source of scarce material if the financial and technological obstacles can be overcome. Asteroids are lumps of metals, rock and dust, sometimes laced with ices and tar, which are the cosmic \"leftovers\" from the solar system's formation about 4.5 billion years ago. There are hundreds of thousands of them, ranging in size from a few yards to hundreds of miles across. Small asteroids are much more numerous than large ones, but even a little, house-sized asteroid should contain metals possibly worth millions of dollars.\r\n\r\nThere are different kinds of asteroids, and they are grouped into three classes from their spectral type – a classification based on an analysis of the light reflected off of their surfaces. Dark, carbon-rich, \"C-type\" asteroids have high abundances of water bound up as hydrated clay minerals. Although these asteroids currently have little economic value since water is so abundant on Earth, they will be extremely important if we decide we want to expand the human presence throughout the solar system.\r\n\r\n\"Water is a critical life-support item for a spacefaring civilization, and it takes a lot of energy to launch it into space,\" says Dante Lauretta of the University of Arizona, Tucson, principal investigator for NASA’s OSIRIS-REx asteroid sample return mission. \"With launch costs currently thousands of dollars per pound, you want to use water already available in space to reduce mission costs. The other thing you can do with water is break it apart into its constituent hydrogen and oxygen, and that becomes rocket fuel, so you could have fuel depots out there where you're mining these asteroids. The other thing C-type asteroids have is organic material – they have a lot of organic carbon, phosphorous and other key elements for fertilizer to grow your food,\" said Lauretta.\r\n\r\nhttps://www.nasa.gov/content/goddard/new-nasa-mission-to-help-us-learn-how-to-mine-asteroids","cover_dy":0},
#		{"id":6,"name":"Earth","description":"An alternative vision of what the future can be if we apply what we already know in order to achieve a sustainable new world civilization.","created_at":"2017-03-21T21:13:42.000Z","updated_at":"2017-04-04T01:21:05.000Z","cover_file_name":"earth-from-space.jpg","cover_content_type":"image/jpeg","cover_file_size":324487,"cover_updated_at":"2017-03-24T00:45:56.000Z","objectives":"1. Realizing the declaration of the world’s resources as being the common heritage of all people.\r\n\r\n2. Transcending the artificial boundaries that currently and arbitrarily separate people.\r\n\r\n3. Replacing money-based nationalistic economies with a resource-based world economy.\r\n\r\n4. Assisting in stabilizing the world’s population through education and voluntary birth control.\r\n\r\n5. Reclaiming and restoring the natural environment to the best of our ability.\r\n\r\n6. Redesigning cities, transportation systems, agricultural industries, and industrial plants so that they are energy efficient, clean, and able to conveniently serve the needs of all people.\r\n\r\n7. Gradually outgrowing corporate entities and governments, (local, national, or supra-national) as means of social management.\r\n\r\n8. Sharing and applying new technologies for the benefit of all nations.\r\n\r\n9. Developing and using clean renewable energy sources.\r\n\r\n10. Manufacturing the highest quality products for the benefit of the world’s people.\r\n\r\n11. Requiring environmental impact studies prior to construction of any mega projects.\r\n\r\n12. Encouraging the widest range of creativity and incentive toward constructive endeavor.\r\n\r\n13. Outgrowing nationalism, bigotry, and prejudice through education.\r\n\r\n14. Eliminating elitism, technical or otherwise.\r\n\r\n15. Arriving at methodologies by careful research rather than random opinions.\r\n\r\n16. Enhancing communication in schools so that our language is relevant to the physical conditions of the world.\r\n\r\n17. Providing not only the necessities of life, but also offering challenges that stimulate the mind while emphasizing individuality rather than uniformity.\r\n\r\n18. Finally, preparing people intellectually and emotionally for the changes and challenges that lie ahead.\r\n\r\nhttps://www.thevenusproject.com/the-venus-project/aims-and-proposals/","cover_dy":0},
#		{"id":7,"name":"Venus","description":"Let’s send piloted, helium-filled airships cruising through the Venusian atmosphere. This could eventually lead to the permanent settlement of Earth's hellishly hot sister planet.","created_at":"2017-03-23T23:57:32.000Z","updated_at":"2017-04-04T01:17:22.000Z","cover_file_name":"venus.jpg","cover_content_type":"image/jpeg","cover_file_size":1138883,"cover_updated_at":"2017-03-24T00:56:24.000Z","objectives":"The overarching HAVOC plan envisions establishing Venus cloud cities in five phases, the first four of which would validate technologies needed for the more ambitious steps to come.\r\n\r\nPhase 1 would involve robotic exploration of the Venusian atmosphere using an unmanned, 102-foot-long (31 meters) airship. In Phase 2, two astronauts would spend 30 days in orbit around Venus. In Phase 3 and Phase 4, two crewmembers would cruise through the skies of Venus in a 423-foot-long (129 m) airship for 30 days and one year, respectively. Permanent settlement would come in Phase 5.\r\n\r\nHAVOC's solar-powered airships would fly at an altitude of about 30 miles, where they'd receive 40 percent more solar energy than Earth receives at its surface.\r\n\r\nThe propeller-driven vehicles would carry a variety of instruments to study Venus' atmosphere. The manned airships would also feature a human habitat and a multistage rocket that would launch the crewmembers back to orbit when their time on Venus was done.\r\n\r\nOnce in orbit, the astronauts would rendezvous with a spacecraft that would take them back to Earth.\r\n\r\nhttp://www.space.com/29140-venus-airship-cloud-cities-incredible-technology.html","cover_dy":100},
#		{"id":8,"name":"Europa","description":"Europa is thought to have a liquid water ocean underneath its icy exterior. Access to this liquid water ocean is a major difficulty, but the abundance of water on Europa is a benefit to any considerations for colonization.","created_at":"2017-03-24T03:17:29.000Z","updated_at":"2017-04-04T01:11:57.000Z","cover_file_name":"europa-1920.jpg","cover_content_type":"image/jpeg","cover_file_size":601161,"cover_updated_at":"2017-03-24T03:17:58.000Z","objectives":"Forewarned is forearmed in science fact and science fiction when it comes to Jupiter's icy moon Europa. Frigid and ice-covered, Europa is believed to harbor a giant liquid ocean beneath its crusty arctic surface, a primordial sea whose tidal motions are driven by Jovian gravity and warmed by intense radiation given off by the giant planet. \r\n\r\nYet despite the planet's fearsome environment, members of the Artemis Society, a private venture dedicated establishing a permanent, self-supporting community on the Moon, also have set their sites on the creation of a human colony at Europa.\r\n\r\nThe group has planned almost everything from how to build communities in subsurface air pockets, to how to program the colonist’s digital watches. Some folks at NASA are skeptical.\r\n\r\n\"Europa is right in the middle of an incredibly deadly radiation belt around Jupiter,\" said Jet Propulsion Laboratory’s Rich Terrile, deputy project scientist for the Europa Orbiter. \"A fairly well shielded human being on the surface of Europa, and even in the vicinity of Europa, would die in about 10 minutes. It would be like standing 30 feet (9 meters) away from the unshielded core of a 10-gigawatt nuclear reactor. It’s just where you really don’t want to be.\" \r\n\r\nDon’t think that the radiation-absorbing ice will protect any intrepid explorers either. According to Terrile, \"if you get beneath maybe 6 feet (2 meters) of ice you’ll be okay. But you’ve got to get to the surface and every 10 minutes is a lethal dose so you don’t have very much time.\"\r\n\r\nThe Artemis plan looks straight at the radiation problem and blinks. \"For the purposes of our mission, we assume that it takes place in an era in which the engineering challenges of providing electromagnetic shielding have been mastered,\" says Peter Kokh, the primary author of the Europa plan.\r\n\r\nHiding in accelerators and under ice \r\n\r\nAny chance deflector shields could protect the explorers? According to JPL's Terrile, \"building these shielded ships is like being inside a VanDeGraph accelerator but these things don't work. You have to build these very, very high-charge gradients around you in order to deflect particles and there's no practical way to do that.\"\r\n\r\nBut recently Kokh has dreamed up an inspiringly simple solution for the radiation problem. \"Callisto is outside the radiation zone,\" he says. \"If you could start with a staging base where you jacket the ship with ice from Callisto, you could have either humans or robots mine the ice. That way you wouldn't have to spend all that fuel to get that shielding from the Earth.\"\r\n\r\nAs for how to survive on Europa's surface, \"you just have to get under the ice fairly quickly,\" he says. \"That's just an engineering detail.\" \r\n\r\nGravity and magnetic data collected by the NASA Galileo orbiter over the past five years have provided increasing evidence that an ocean exists underneath Europa's uniform 5- to 62-mile (10- to 100-kilometer) thick coat of ice. The possible ocean on Europa may contain more liquid water than all the oceans on Earth combined. \r\n\r\nhttp://www.freerepublic.com/focus/chat/691006/posts","cover_dy":0}
#	])


